### ISSUE TITLE
Absolute paths used

### ISSUE THREAD

**Issue by bsongis** [Benno00/swmap#4]
There should be no `/scripts/swmap/` anywhere, the user should be allowed to rename the directory. It's better to use relative paths, like `./error.txt`

**Comment by Benno00** [comment]
ok I will adjust it

**Comment by bsongis** [comment]
Even in 1.6.0 ?

**Comment by bsongis** [comment]
In which handler is it called? write?

**Comment by Benno00** [comment]
here 
```

        local function load_data(widget,na)
	widget.global= storage.read("global")
	if widget.global==nil then 
		widget.global=false
	end
	--print("widget.global:",widget.global)
	
	if na==nil then na=model.name()..".lua" end
	if widget.global==true then na="global.lua" end
	
	
	local modellpath="./modelle/"
	file=modellpath..model.name()..".lua"
	if os.stat(file) then 
		print(debug_col[2].."Version:".. sys.version.."  file available:",file,debug_col[1])
	else
		print(debug_col[2].."Version:".. sys.version.."  file not available:",file,debug_col[1])
	end


```

**Comment by bsongis** [comment]
It will be fixed in a last minute fix for the 1.6.0 release

**Comment by Benno00** [comment]
ok, thank you

**Comment by Benno00** [comment]
Hello Bertrand,
for your information: 
the same problem exists with the function init, function read and as already known in the function write
in the functions create, wakeup and paint it works

**Comment by Benno00** [comment]
Hello Bertrand,
it works now, thank you
