### ISSUE TITLE
write_data() resources

### ISSUE THREAD

**Issue by bsongis** [Benno00/swmap#6]
This function will be possibly called a lot! I am afraid that this implementation doesn't slow down the radio!

**Comment by Benno00** [comment]
the function is always called when there is a change in the Configure(widget), I will think of another possibility

**Comment by bsongis** [comment]
I discover that the function has been changed recently, it was very dangerous in the version that Lothar sent me some days ago. Now it is not optimized, but should not explain a memory leak (which was the case before with the out_txt variable)

**Comment by bsongis** [comment]
These lines from create_table(), were possibly called very often:

```lua
out_txt=out_txt.."\n".."TYP;Name \n"
out_txt=out_txt.."-------------------------- \n"
```

**Comment by Benno00** [comment]
strange, I haven't changed anything about it.
but I'll take a closer look and maybe optimize it
out_text is intended for error messages I will revise accordingly
Thank you for your advice

**Comment by bsongis** [comment]
Understoo. But even in case of error, it is not allowed to have a variable which just grows. Perhaps you could write a file in append mode to dump the error?

**Comment by Benno00** [comment]
I have now adjusted it accordingly.
Thank you for the tip
